In [1]:
import numpy as np
import pandas as pd

In [2]:
train = pd.read_csv('../input/customerattritionprediction/train.csv')
test = pd.read_csv('../input/customerattritionprediction/test.csv')
sample_submission = pd.read_csv('../input/customerattritionprediction/Sample Submission.csv')

In [3]:
train

ID     sex Aged Married TotalDependents  ServiceSpan  \
0     B60LHTZLLPFU4IULNPUF  Female   No      No             Yes           48   
1     1RUJ7ONYZHYTWKOKO1SD    Male   No     Yes              No           45   
2     DZ9EEOQWSN0MYCBUPAM5    Male  Yes     Yes              No           59   
3     YZ43L1UQUQACTL1PXXZG    Male   No      No              No           14   
4     6P28152QGF60PDLSCB9M  Female   No     Yes             Yes           25   
...                    ...     ...  ...     ...             ...          ...   
6333  Y7U717HO87PCW6XXIQA1  Female  Yes      No              No            3   
6334  NGY3WOQ0OT1P4RHAR0PT  Female  Yes      No              No           -1   
6335  ZBBW7H8AYLZJ2HK5TBBJ    Male   No      No             Yes           18   
6336  BUE75NSSLT2S2URTKZRN    Male   No     Yes              No           46   
6337  IRFAYIAO820RIX2GUFFF  Female   No      No              No           60   

     MobileService            4GService CyberProtection HardwareSupport  \
0              Yes       Wifi Broadband              No             Yes   
1              Yes       Wifi Broadband              No              No   
2              Yes       Wifi Broadband             Yes              No   
3              Yes       Wifi Broadband              No              No   
4              Yes       Wifi Broadband              No             Yes   
...            ...                  ...             ...             ...   
6333           Yes       Wifi Broadband              No             Yes   
6334           Yes  Satellite Broadband              No              No   
6335           Yes                   No              No              No   
6336           Yes                   No              No              No   
6337           Yes  Satellite Broadband              No              No   

     TechnicalAssistance FilmSubscription SettlementProcess  QuarterlyPayment  \
0                    Yes               No             Check         96.259802   
1                     No              Yes              Bank         18.876470   
2                    Yes               No              Card        106.016057   
3                     No               No             Check         80.108839   
4                     No              Yes             Check         51.529773   
...                  ...              ...               ...               ...   
6333                  No              Yes              Card        100.391595   
6334                  No              Yes              Bank         44.782165   
6335                  No               No        Electronic         35.941713   
6336                  No              Yes              Card         94.762984   
6337                  No               No              Bank         94.337343   

      GrandPayment CustomerAttrition  
0      4628.129119               Yes  
1       922.085998                No  
2      6205.891129               Yes  
3      1248.655391                No  
4      1285.321277                No  
...            ...               ...  
6333    441.914530               Yes  
6334     45.308180                No  
6335    552.181341               Yes  
6336   4563.812326                No  
6337   5756.542013                No  

[6338 rows x 16 columns]

In [4]:
train.loc[pd.isna(train['GrandPayment']), :].index

Int64Index([643, 1169, 1186, 2281, 3611, 3918, 5579, 5742, 5796, 6203], dtype='int64')

In [5]:
test.loc[pd.isna(test['GrandPayment']), :].index

Int64Index([532], dtype='int64')

In [6]:
#train['GrandPayment'].fillna(2290.544,inplace=True)
#test['GrandPayment'].fillna(2290.544,inplace=True)
for i in [643, 1169, 1186, 2281, 3611, 3918, 5579, 5742, 5796, 6203]:
    train['GrandPayment'].iloc[i] = train['ServiceSpan'].iloc[i]*train['QuarterlyPayment'].iloc[i] 
    
test['GrandPayment'].iloc[532] = test['ServiceSpan'].iloc[532]*test['QuarterlyPayment'].iloc[532]

/opt/conda/lib/python3.7/site-packages/pandas/core/indexing.py:1637: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)


In [7]:
train['ServiceSpan'].unique()

array([48, 45, 59, 14, 25, 27, 53,  0,  1, 46, 67, 24, 61, 54,  9, 30, 18,
        5, 64,  3, 41, 40, 31, 21, 15,  6, 69, 72, 33, 71,  2, 36,  8, 37,
       34, 28, -1, 60, 22, 68, 11, 39, 58, 10, 50,  4, 44, 49, 38, 55, 51,
       16, 65, 13, 26, 19, 57, 70, 73, 42, 35, 62, 23, 56, 47, 63, 32, 29,
        7, 20, 43, 12, 52, 17, 66, -2])

In [8]:
for i in range(len(train)):
    if(train['ServiceSpan'].iloc[i]==-1 or train['ServiceSpan'].iloc[i]==-2):
        train['ServiceSpan'].iloc[i] = int(train['GrandPayment'].iloc[i]/train['QuarterlyPayment'].iloc[i])

In [9]:
train.drop(['ID' ,'CyberProtection', 'HardwareSupport', 'TotalDependents','SettlementProcess'], axis=1, inplace=True)
test.drop(['ID', 'CyberProtection', 'HardwareSupport', 'TotalDependents','SettlementProcess'], axis=1, inplace=True)

In [10]:
train.head(1)

sex Aged Married  ServiceSpan MobileService       4GService  \
0  Female   No      No           48           Yes  Wifi Broadband   

  TechnicalAssistance FilmSubscription  QuarterlyPayment  GrandPayment  \
0                 Yes               No         96.259802   4628.129119   

  CustomerAttrition  
0               Yes

In [11]:
a=[]
b=[]

In [12]:
for i in range(len(train)):
    if train['Aged'].iloc[i]=='Yes' and train['Married'].iloc[i]=='Yes':
        a.append(1)
    else:
        a.append(0)
        
for i in range(len(test)):
    if test['Aged'].iloc[i]=='Yes' and test['Married'].iloc[i]=='Yes':
        b.append(1)
    else:
        b.append(0)
            

In [13]:
train['Aged_Married'] = a
test['Aged_Married'] = b

In [14]:
train = pd.get_dummies(train, columns=['sex', 'Aged', 'Married', 'MobileService', '4GService', 'TechnicalAssistance', 'FilmSubscription'])

In [15]:
test = pd.get_dummies(test, columns=['sex', 'Aged', 'Married', 'MobileService', '4GService', 'TechnicalAssistance', 'FilmSubscription'])

In [16]:
from sklearn import preprocessing 
label_encoder = preprocessing.LabelEncoder() 

In [17]:
train['CustomerAttrition']= label_encoder.fit_transform(train['CustomerAttrition'])

In [18]:
train.head(2)

ServiceSpan  QuarterlyPayment  GrandPayment  CustomerAttrition  \
0           48         96.259802   4628.129119                  1   
1           45         18.876470    922.085998                  0   

   Aged_Married  sex_Female  sex_Male  Aged_No  Aged_Yes  Married_No  \
0             0           1         0        1         0           1   
1             0           0         1        1         0           0   

   Married_Yes  MobileService_No  MobileService_Yes  4GService_No  \
0            0                 0                  1             0   
1            1                 0                  1             0   

   4GService_Satellite Broadband  4GService_Wifi Broadband  \
0                              0                         1   
1                              0                         1   

   TechnicalAssistance_No  TechnicalAssistance_Yes  FilmSubscription_No  \
0                       0                        1                    1   
1                       1                        0                    0   

   FilmSubscription_Yes  
0                     0  
1                     1

In [19]:
from sklearn.model_selection import train_test_split
X_res, X_test, y_res, y_test = train_test_split(train.drop('CustomerAttrition',axis=1), train['CustomerAttrition'], test_size=0.2, random_state=42)

In [20]:
from imblearn.over_sampling import ADASYN
sm = ADASYN(random_state = 2)
X_train, y_train = sm.fit_resample(X_res, y_res)

In [21]:
from sklearn.preprocessing import StandardScaler
SC = StandardScaler()
X_train = SC.fit_transform(X_train)
X_test = SC.transform(X_test)

In [22]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(X_train, y_train)

In [44]:
y_pred = reg.predict(X_test)

In [45]:
y_pred

array([0.16317221, 0.21614283, 0.57074948, ..., 0.28265817, 0.4455778 ,
       0.50287552])

In [56]:
y_test = np.array(y_test)

In [57]:
y_pred2 = []
for i in range(len(y_pred)):
    if y_pred[i]<0.5:
        y_pred2.append('No')
    else:
        y_pred2.append('Yes')
y_test2 = []
for i in range(len(y_test)):
    if y_test[i]<0.5:
        y_test2.append('No')
    else:
        y_test2.append('Yes')        

In [60]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test2, y_pred2)

0.8012618296529969

In [61]:
prediction = reg.predict(test)

In [65]:
prediction2 = []
for i in range(len(prediction)):
    if prediction[i]>0.5:
        prediction2.append('No')
    else:
        prediction2.append('Yes')

In [67]:
sub = sample_submission.copy()
sub['CustomerAttrition'] = prediction2
sub
sub.to_csv('submission_new2.csv', index=False)

In [70]:
sub['CustomerAttrition'].value_counts()

No     683
Yes     22
Name: CustomerAttrition, dtype: int64

In [71]:
import lightgbm as lgb
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier
import xgboost as xgb
from catboost import CatBoostClassifier

In [72]:

hyper_params1 = { "n_estimators": 60,'n_jobs':-1, 'learning_rate':0.5}

hyper_params2 = {'n_estimators': 60,'n_jobs':-1}

hyper_params3 = {'n_estimators':60, 'n_jobs':-1,'learning_rate':0.5 }

hyper_params4 = {'iterations':60,'learning_rate':0.5}

In [73]:
model1 = lgb.LGBMClassifier(**hyper_params1)
model2 = RandomForestClassifier(**hyper_params2)
model3 = xgb.XGBClassifier(**hyper_params3)
model4 = CatBoostClassifier(**hyper_params4)

In [74]:
estimator = []
estimator.append(('lgb', model1))
estimator.append(('rf',  model2)) 
estimator.append(('xgb', model3))
estimator.append(('cbr', model4)) 

vot = VotingClassifier(estimators = estimator) 
vot.fit(X_train, y_train)

/opt/conda/lib/python3.7/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[09:25:34] WARNING: ../src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
0:	learn: 0.5377757	total: 57.2ms	remaining: 3.37s
1:	learn: 0.4659659	total: 60.1ms	remaining: 1.74s
2:	learn: 0.4120879	total: 63.1ms	remaining: 1.2s
3:	learn: 0.3862659	total: 66ms	remaining: 923ms
4:	learn: 0.3700521	total: 69.2ms	remaining: 761ms
5:	learn: 0.3524082	total: 72.5ms	remaining: 653ms
6:	learn: 0.3394752	total: 75.5ms	remaining: 572ms
7:	learn: 0.3341146	total: 78.5ms	remaining: 510ms
8:	learn: 0.3310963	total: 81.7ms	remaining: 463ms
9:	learn: 0.3261769	total: 85ms	remaining: 425ms
10:	learn: 0.3208992	total: 88.5ms	remaining: 394ms
11:	learn: 0.3171898	total: 92ms	remaining: 368ms
12:	learn: 0.3160168	total: 95.1ms	remaining: 344ms
13:	learn: 0.3140570	total: 98.3ms	remaining: 323ms
14:	learn: 0.3124363	total: 102ms	rem

VotingClassifier(estimators=[('lgb',
                              LGBMClassifier(learning_rate=0.5,
                                             n_estimators=60)),
                             ('rf',
                              RandomForestClassifier(n_estimators=60,
                                                     n_jobs=-1)),
                             ('xgb',
                              XGBClassifier(base_score=None, booster=None,
                                            colsample_bylevel=None,
                                            colsample_bynode=None,
                                            colsample_bytree=None, gamma=None,
                                            gpu_id=None, importance_type='gain',
                                            interaction_constraints=None,
                                            learning_rate=...
                                            max_delta_step=None, max_depth=None,
                                       

In [75]:
y_pred = vot.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

/opt/conda/lib/python3.7/site-packages/xgboost/data.py:114: UserWarning: Use subset (sliced data) of np.ndarray is not recommended because it will generate extra copies and increase memory consumption
  "because it will generate extra copies and increase " +


0.7894321766561514

In [85]:
prediction = vot.predict(test)
pred = label_encoder.inverse_transform(prediction)
sub = sample_submission.copy()
sub['CustomerAttrition'] = pred
sub
sub.to_csv('submission_new4.csv', index=False)

/opt/conda/lib/python3.7/site-packages/xgboost/data.py:114: UserWarning: Use subset (sliced data) of np.ndarray is not recommended because it will generate extra copies and increase memory consumption
  "because it will generate extra copies and increase " +


In [76]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0).fit(X_train, y_train)

In [77]:
y_pred = clf.predict(X_test)

In [78]:
y_pred

array([0, 0, 1, ..., 0, 0, 1])

In [79]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.8020504731861199

In [82]:
prediction = clf.predict(test)

In [81]:
prediction

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [ ]:
sub = sample_submission.copy()
sub['CustomerAttrition'] = pred
sub
sub.to_csv('submission_new5.csv', index=False)